apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::149616845329:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-I21UDRVSDC40
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::149616845329:role/UdacityFlaskDeployCBKubectlRole
      username: build  
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-02-17T16:09:55Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:mapRoles: {}
        f:mapUsers: {}
    manager: eksctl.exe
    operation: Update
    time: "2021-02-17T16:09:55Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1478"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: d8295deb-6320-4e11-b75f-d0689d97e630
